server: "tcp://127.0.0.1:9000"
test: false
certfile: "/etc/letsencrypt/live/mmo.unit.dev/cert.pem"
keyfile: "/etc/letsencrypt/live/mmo.unit.dev/privkey.pem"

#server: "tcp://127.0.0.1:9000"
#test: true
#certfile: "cert.pem"
#keyfile: "privkey.pem"

#server: "tcp://127.0.0.1:9000"
#test: true
#certfile: "./build/cert.pem"
#keyfile: "./build/privkey.pem"
